---
Name: 'seoextensions'
---
# Include required CSS and JS
LeftAndMain:
  extra_requirements_css:
    - micschk/silverstripe-liveseo:client/css/seo.css
  extra_requirements_javascript:
    - micschk/silverstripe-liveseo:client/liveseo/js/seo.js

SiteTree:
  extensions:
    - Restruct\Silverstripe\LiveSEO\SeoObjectExtension
SiteConfig:
  extensions:
    - Restruct\Silverstripe\LiveSEO\SeoSiteConfig
# Example of how to exclude extra page types from showing the SEO tab:
# SeoSiteTreeExtension:
#   excluded_page_types:
#     - 'SomePage'

---
Name: 'seositemaps'
Only:
  moduleexists: 'wilr/campaign-admin'
---
# optimize SiteMaps module (if installed)
Wilr\GoogleSitemaps\GoogleSitemap:
  enabled: true
  objects_per_sitemap: 1000
  google_notification_enabled: true
  use_show_in_search: true