---
Name: 'seoextensions'
---
SiteTree:
  extensions:
    - 'SeoSiteTreeExtension'
SiteConfig:
  extensions:
    - 'SeoSiteConfigExtension'

# optimize some other modules
GoogleSitemap:
  google_notification_enabled: true

# Example of how to exclude extra page types from showing the SEO tab:
# SeoSiteTreeExtension:
#   excluded_page_types:
#     - 'SomePage'
